apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
spec:
  template:
    spec:
      containers:
      - name: broadcaster
        env:
        - name: DISCORD_WEBHOOK_URL
          value: ""  # Disable Discord in staging - broadcaster will only log
